import type { Project, SkillGroup, CareerEntry } from "./types";

export const projects: Project[] = [
  {
    id: "smart-cric",
    title: "Smart Cric",
    category: "ai-cv",
    tags: ["YOLO", "OpenCV", "Python", "Real-time Tracking"],
    problem: "// TODO: replace with real content",
    build: "// TODO: replace with real content",
    role: "// TODO: replace with real content",
    outcome: "// TODO: replace with real content",
    image: "/images/smart-cric.jpg",
    href: "#",
    featured: true,
  },
  {
    id: "facial-attendance",
    title: "Facial Attendance System",
    category: "ai-cv",
    tags: ["MediaPipe", "OpenCV", "Python", "Face Recognition"],
    problem: "// TODO: replace with real content",
    build: "// TODO: replace with real content",
    role: "// TODO: replace with real content",
    outcome: "// TODO: replace with real content",
    image: "/images/facial-attendance.jpg",
    href: "#",
    featured: true,
  },
  {
    id: "fullstack-app-1",
    title: "// TODO: Full-Stack Project Title",
    category: "product",
    tags: ["Next.js", "Supabase", "TypeScript", "Tailwind"],
    problem: "// TODO: replace with real content",
    build: "// TODO: replace with real content",
    role: "// TODO: replace with real content",
    outcome: "// TODO: replace with real content",
    image: "/images/project-3.jpg",
    href: "#",
    featured: false,
  },
  {
    id: "fullstack-app-2",
    title: "// TODO: Full-Stack Project Title",
    category: "product",
    tags: ["React Native", "Expo", "NestJS", "PostgreSQL"],
    problem: "// TODO: replace with real content",
    build: "// TODO: replace with real content",
    role: "// TODO: replace with real content",
    outcome: "// TODO: replace with real content",
    image: "/images/project-4.jpg",
    href: "#",
    featured: false,
  },
  {
    id: "automation-tool",
    title: "// TODO: Automation/AI Integration Project",
    category: "product",
    tags: ["n8n", "API Integration", "Node.js"],
    problem: "// TODO: replace with real content",
    build: "// TODO: replace with real content",
    role: "// TODO: replace with real content",
    outcome: "// TODO: replace with real content",
    image: "/images/project-5.jpg",
    href: "#",
    featured: false,
  },
];

export const skills: SkillGroup[] = [
  {
    tier: "AI / Computer Vision",
    skills: [
      "Python",
      "OpenCV",
      "PyTorch",
      "TensorFlow",
      "YOLO",
      "MediaPipe",
      "Object Detection",
      "Real-time Tracking",
      "Pose Estimation",
      "Image Segmentation",
    ],
  },
  {
    tier: "Full-Stack / Product",
    skills: [
      "Next.js",
      "React",
      "React Native (Expo)",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "NestJS",
      "Express",
      "Supabase",
      "PostgreSQL",
      "Drizzle ORM",
      "Vercel",
      "Turborepo",
      "Git",
    ],
  },
  {
    tier: "AI Integration / Automation",
    skills: ["n8n", "Agentic Workflows", "API Design & Integration"],
  },
];

export const career: CareerEntry[] = [
  {
    company: "Intermarket Knit",
    role: "// TODO: replace with real role title",
    period: "// TODO: replace with real dates",
    summary: "// TODO: replace with real content",
  },
  {
    company: "Heapware",
    role: "// TODO: replace with real role title",
    period: "// TODO: replace with real dates",
    summary: "// TODO: replace with real content",
  },
  {
    company: "DevNodes",
    role: "// TODO: replace with real role title",
    period: "// TODO: replace with real dates",
    summary: "// TODO: replace with real content",
  },
];
